// 스타일
#define GSS_HORZ 1
#define GSS_VERT 2

// 메시지
#define GSM_SETRANGE WM_USER + 101
#define GSM_GETRANGEHI WM_USER + 102
#define GSM_GETRANGELOW WM_USER + 103
#define GSM_SETPOS WM_USER + 104
#define GSM_GETPOS WM_USER + 105
#define GSM_SETTSIZE WM_USER + 106
#define GSM_GETTSIZE WM_USER + 107
#define GSM_SETTGAP WM_USER + 108
#define GSM_GETTGAP WM_USER + 109
#define GSM_SETBACKCOLOR WM_USER + 110
#define GSM_SETTHUMBCOLOR WM_USER + 111

